cc_library(
    name = "vmos-control",
    srcs = ["PCA9685.cpp"],
    hdrs = ["PCA9685.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core:vmos-core",
        "//hardware/i2c:vmos-i2c",
    ],
)