cc_library(
    name = "vmos-hardware",
    srcs = ["vmos-bno055.cpp"],
    hdrs = ["hello-time.h"],
    visibility = ["//main:__pkg__"],
    deps = [
        "//core/threading:vmos-threading",
    ]
)

