cc_library(
    name = "vmos-hardware",
    visibility = ["//visibility:public"],
    deps = [
        "//core/logging:vmos-logging",
        "//hardware/i2c:vmos-i2c",
        "//hardware/sensors:vmos-sensors",
    ],
)

