cc_library(
    name = "vmos-core",
    visibility = ["//visibility:public"],
    deps = [
        "//core/threading:vmos-threading",
        "//core/math:vmos-math",
        "//core/logging:vmos-logging",
    ],
)

