cc_library(
    name = "vmos-http",
    srcs = glob(
        ["*.cpp"],
    ),
    hdrs = glob([
        "*.h"
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//core:vmos-core"
    ],
)