cc_library(
    name = "vmos-threading",
    srcs = ["message_queue.cpp","threading.cpp"],
    hdrs = ["message_queue.hpp","threading.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/math:vmos-math",
        "//core/logging:vmos-logging",
    ],
)

