cc_library(
    name = "vmos-sensors",
    srcs = ["BNO055.cpp"],
    hdrs = ["BNO055.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core:vmos-core",
        "//hardware/i2c:vmos-i2c",
    ],
)